#!/usr/bin/env bash
set -euo pipefail

# rpay one-command deployment script
# Usage: PUBLIC_URL=https://your-domain DB_URL=mysql://rpay:pass@127.0.0.1:3306/rpay ./scripts/deploy.sh
# Builds, installs binary, creates systemd service, and starts rpay.
# Run this script AFTER ./scripts/init-db.sh has been completed.

# ---------- config ----------
INSTALL_DIR="${INSTALL_DIR:-/opt/services/rpay}"
LISTEN_ADDR="${LISTEN_ADDR:-127.0.0.1:16889}"
PUBLIC_URL="${PUBLIC_URL:?  set PUBLIC_URL=https://your-domain before running}"
DB_URL="${DB_URL:-}"
DB_URL_FILE="${DB_URL_FILE:-${INSTALL_DIR}/secrets/database-url}"
SERVICE_USER="${SERVICE_USER:-rpay}"
SERVICE_GROUP="${SERVICE_GROUP:-rpay}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$SCRIPT_DIR/.."

# ---------- steps ----------
echo "==> [0/8] Checking prerequisites..."
if ! command -v cargo &>/dev/null; then
    echo "    Rust toolchain not found. Install with:"
    echo "    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
    exit 1
fi
if ! command -v mysql &>/dev/null; then
    echo "    Warning: mysql client not found (needed for init-db.sh, not for deploy)"
fi

echo "==> [1/8] Building rpay (release)..."
cd "$REPO_DIR"
cargo build --release

echo "==> [2/8] Creating system user and directories..."
if ! id -u "$SERVICE_USER" &>/dev/null; then
    useradd -r -s /usr/sbin/nologin -d "$INSTALL_DIR" "$SERVICE_USER"
fi
mkdir -p "$INSTALL_DIR/bin" "$INSTALL_DIR/secrets" "$INSTALL_DIR/data" "$INSTALL_DIR/logs" "$INSTALL_DIR/backups"

echo "==> [3/8] Installing binary..."
cp "$REPO_DIR/target/release/rpay" "$INSTALL_DIR/bin/rpay"
chmod 755 "$INSTALL_DIR/bin/rpay"
chown "$SERVICE_USER:$SERVICE_GROUP" "$INSTALL_DIR/bin/rpay"

echo "==> [4/8] Setting up database URL file..."
if [ -n "$DB_URL" ]; then
    echo -n "$DB_URL" > "$DB_URL_FILE"
    echo "    Created $DB_URL_FILE from DB_URL env var"
elif [ ! -f "$DB_URL_FILE" ]; then
    echo "    Database URL file not found at $DB_URL_FILE"
    echo "    Either:"
    echo "      a) Set DB_URL env var:  DB_URL=mysql://rpay:PASSWORD@127.0.0.1:3306/rpay ./scripts/deploy.sh"
    echo "      b) Or create it manually:  echo -n 'mysql://rpay:PASSWORD@127.0.0.1:3306/rpay' > $DB_URL_FILE"
    exit 1
fi
chmod 600 "$DB_URL_FILE"
chown "$SERVICE_USER:$SERVICE_GROUP" "$DB_URL_FILE"

echo "==> [5/8] Installing systemd service..."
SERVICE_FILE="$REPO_DIR/deploy/rpay.service"
TMP_SERVICE=$(mktemp)
sed "s|https://rpay.example.com|${PUBLIC_URL}|g; s|/opt/services/rpay|${INSTALL_DIR}|g; s|User=rpay|User=${SERVICE_USER}|g; s|Group=rpay|Group=${SERVICE_GROUP}|g" "$SERVICE_FILE" > "$TMP_SERVICE"
cp "$TMP_SERVICE" /etc/systemd/system/rpay.service
rm -f "$TMP_SERVICE"
systemctl daemon-reload

echo "==> [6/8] Enabling and starting service..."
systemctl enable rpay
systemctl restart rpay

echo "==> [7/8] Verifying..."
sleep 2
if systemctl is-active --quiet rpay; then
    echo "    rpay is running!"
else
    echo "    rpay failed to start. Check: journalctl -u rpay -n 20"
    exit 1
fi

echo "==> [8/8] Health check..."
if curl -sf "http://${LISTEN_ADDR}/healthz" >/dev/null 2>&1; then
    echo "    Health check passed!"
else
    echo "    Warning: health check failed (service may still be starting)"
fi

echo ""
echo "============================================"
echo "  Deployment complete!"
echo "============================================"
echo ""
echo "  Service:  systemctl status rpay"
echo "  Logs:     journalctl -u rpay -f"
echo "  Admin:    ${PUBLIC_URL}/admin"
echo "  Health:   curl http://${LISTEN_ADDR}/healthz"
echo ""
echo "  Next: Log in to /admin with the credentials"
echo "  generated by ./scripts/init-db.sh"
echo "============================================"
