#!/usr/bin/env bash
set -euo pipefail

# rpay one-command deployment script
# Usage: ./scripts/deploy.sh
# Builds, installs binary, creates systemd service, and starts rpay.
# Run this script AFTER ./scripts/init-db.sh has been completed.

# ---------- config ----------
INSTALL_DIR="${INSTALL_DIR:-/opt/services/rpay}"
LISTEN_ADDR="${LISTEN_ADDR:-127.0.0.1:16889}"
PUBLIC_URL="${PUBLIC_URL:?  set PUBLIC_URL=https://your-domain before running}"
DB_URL_FILE="${DB_URL_FILE:-${INSTALL_DIR}/secrets/database-url}"
SERVICE_USER="${SERVICE_USER:-rpay}"
SERVICE_GROUP="${SERVICE_GROUP:-rpay}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$SCRIPT_DIR/.."

# ---------- steps ----------
echo "==> [1/7] Building rpay (release)..."
cd "$REPO_DIR"
cargo build --release

echo "==> [2/7] Creating system user and directories..."
if ! id -u "$SERVICE_USER" &>/dev/null; then
    useradd -r -s /usr/sbin/nologin -d "$INSTALL_DIR" "$SERVICE_USER"
fi
mkdir -p "$INSTALL_DIR/bin" "$INSTALL_DIR/secrets" "$INSTALL_DIR/data" "$INSTALL_DIR/logs" "$INSTALL_DIR/backups"
chown -R "$SERVICE_USER:$SERVICE_GROUP" "$INSTALL_DIR"

echo "==> [3/7] Installing binary..."
cp "$REPO_DIR/target/release/rpay" "$INSTALL_DIR/bin/rpay"
chmod 755 "$INSTALL_DIR/bin/rpay"
chown "$SERVICE_USER:$SERVICE_GROUP" "$INSTALL_DIR/bin/rpay"

echo "==> [4/7] Checking database URL file..."
if [ ! -f "$DB_URL_FILE" ]; then
    echo "    Database URL file not found at $DB_URL_FILE"
    echo "    Create it with:"
    echo "    echo -n 'mysql://rpay:PASSWORD@127.0.0.1:3306/rpay' > $DB_URL_FILE"
    echo "    chmod 600 $DB_URL_FILE"
    echo "    chown $SERVICE_USER:$SERVICE_GROUP $DB_URL_FILE"
    exit 1
fi
chmod 600 "$DB_URL_FILE"
chown "$SERVICE_USER:$SERVICE_GROUP" "$DB_URL_FILE"

echo "==> [5/7] Installing systemd service..."
SERVICE_FILE="$REPO_DIR/deploy/rpay.service"
TMP_SERVICE=$(mktemp)
sed "s|https://rpay.example.com|${PUBLIC_URL}|g; s|/opt/services/rpay|${INSTALL_DIR}|g" "$SERVICE_FILE" > "$TMP_SERVICE"
cp "$TMP_SERVICE" /etc/systemd/system/rpay.service
rm -f "$TMP_SERVICE"
systemctl daemon-reload

echo "==> [6/7] Enabling and starting service..."
systemctl enable rpay
systemctl restart rpay

echo "==> [7/7] Verifying..."
sleep 2
if systemctl is-active --quiet rpay; then
    echo "    rpay is running!"
else
    echo "    rpay failed to start. Check: journalctl -u rpay -n 20"
    exit 1
fi

echo ""
echo "============================================"
echo "  Deployment complete!"
echo "============================================"
echo ""
echo "  Service:  systemctl status rpay"
echo "  Logs:     journalctl -u rpay -f"
echo "  Admin:    ${PUBLIC_URL}/admin"
echo "  Health:   curl http://127.0.0.1:16889/healthz"
echo ""
echo "  Next: Log in to /admin with the credentials"
echo "  generated by ./scripts/init-db.sh"
echo "============================================"
